import {newModules,newCatalog} from './program-v2';
export const modules=newModules;
export const catalog=newCatalog;
const legacyModules = [
{id:'fondations',title:'Fondations IA & ChatGPT',description:'Prenez en main votre nouvel assistant de travail.',level:'Fondamentaux',color:'mint',symbol:'✳',topics:['Votre premier assistant immobilier','Un prompt qui produit un vrai livrable','Projets, fichiers et méthode de travail']},
{id:'quebec',title:'Courtier augmenté au Québec',description:'Gardez le jugement professionnel au centre de votre pratique.',level:'Essentiel',color:'sand',symbol:'⌂',topics:['Cadre du courtage et responsabilités','Confidentialité, Loi 25 et données clients','Publicité et images générées par IA']},
{id:'marque',title:'Votre marque, votre voix',description:'Une identité reconnaissable, jusque dans vos prompts.',level:'Fondamentaux',color:'lavender',symbol:'Aa',topics:['Positionnement et clientèle cible','Votre guide de voix et correction de texte','Traduction français–anglais contextualisée']},
{id:'proprietes',title:'Des propriétés bien présentées',description:'Transformez les faits vérifiés en annonces convaincantes.',level:'Pratique',color:'sand',symbol:'⌂',topics:['Description de propriété et variantes','Mesures, tableaux et image vers texte','Plan de mise en marché multicanal']},
{id:'documents',title:'Lire les dossiers avec l’IA',description:'Analysez sans perdre la source ni les nuances.',level:'Pratique',color:'mint',symbol:'≡',topics:['Résumé de rapport d’inspection','Déclaration de copropriété et questions utiles','Dossier vendeur et préparation de rencontre']},
{id:'social',title:'Réseaux sociaux organiques',description:'Facebook, Instagram, LinkedIn : une présence utile.',level:'Pratique',color:'lavender',symbol:'#',topics:['Calendrier Facebook et contenu local','Instagram, carrousels et engagement','LinkedIn, blogue et référencement local']},
{id:'video',title:'Images, vidéos & accroches',description:'Créez des contenus qui captent et méritent l’attention.',level:'Création',color:'mint',symbol:'▷',topics:['Scripts Reels, TikTok et vidéo de propriété','Accroches visuelles, textuelles et audio','Images IA et production dans Canva']},
{id:'publicite',title:'Publicité & acquisition',description:'Un parcours clair du premier clic à la conversation.',level:'Avancé',color:'sand',symbol:'↗',topics:['Campagne payante et angles créatifs','Page de destination et formulaire','Mesure de performance et tests A/B']},
{id:'infolettre',title:'Infolettres & relation client',description:'Entretenez la confiance, un message pertinent à la fois.',level:'Pratique',color:'lavender',symbol:'@',topics:['Créer une infolettre qui rend service','Séquences courriel et consentement','SMS saisonniers et suivi après transaction']},
{id:'automatisation',title:'Automatiser votre quotidien',description:'CRM, Make et Zapier avec des points de contrôle.',level:'Avancé',color:'mint',symbol:'⚡',topics:['Dessiner un workflow fiable','Connecter formulaires, CRM et infolettres','SOP et assistant de soutien interne']},
{id:'gpt',title:'Votre écosystème ChatGPT',description:'Concevez vos assistants et reliez vos outils.',level:'Avancé',color:'lavender',symbol:'✳',topics:['Construire votre GPT immobilier spécialisé','Actions GPT, API et outils connectés','Tester, versionner et améliorer vos prompts']},
{id:'final',title:'Votre système marketing complet',description:'Un projet concret, prêt à être évalué par votre coach.',level:'Projet final',color:'sand',symbol:'✓',topics:['Stratégie de croissance sur 90 jours','Simulation complète : un condo à Québec','Portfolio, soutenance et amélioration continue']}
];
const legacyCatalog=legacyModules.flatMap((m,mi)=>m.topics.map((title,i)=>({id:`${m.id}-${i+1}`,moduleId:m.id,moduleIndex:mi,title,number:i+1,minutes:35+i*10,preview:mi===0})));
export const sources=[
{id:'oaciq',name:'OACIQ — Publicité et utilisation de l’IA',url:'https://www.oaciq.com/fr/titulaires-de-permis/lignes-directrices/ligne-directrice-representation-sollicitation-promotion-et-publicite/publicite/',summary:'Exactitude des annonces, transparence des images IA et responsabilité du courtier.'},
{id:'ia',name:'OACIQ — Guide d’utilisation d’un système d’IA',url:'https://www.oaciq.com/media/32kp2fkv/guide-ia-vfra.pdf',summary:'Vérification, information, confidentialité et supervision des outils IA.'},
{id:'loi',name:'Légis Québec — Loi sur le courtage immobilier',url:'https://www.legisquebec.gouv.qc.ca/fr/document/lc/C-73.2',summary:'Texte officiel du cadre québécois du courtage.'},
{id:'vie',name:'Légis Québec — Protection des renseignements personnels',url:'https://www.legisquebec.gouv.qc.ca/fr/document/lc/P-39.1',summary:'Loi sur le secteur privé, modifiée notamment par la Loi 25.'},
{id:'cai',name:'CAI — Collecte de renseignements personnels',url:'https://www.cai.gouv.qc.ca/protection-renseignements-personnels/information-entreprises-privees/collecte-renseignements-personnels_entreprises',summary:'Nécessité, transparence et information des personnes.'},
{id:'lcap',name:'CRTC — Consentement et Loi canadienne anti-pourriel',url:'https://crtc.gc.ca/fra/com500/guide.htm',summary:'Règles fédérales applicables au Québec pour les messages électroniques commerciaux.'},
{id:'actions',name:'OpenAI — GPT Actions',url:'https://developers.openai.com/api/docs/actions/introduction',summary:'Connexion d’un GPT à une API par un schéma OpenAPI et une authentification.'},
{id:'prompts',name:'OpenAI — Ingénierie des prompts',url:'https://developers.openai.com/api/docs/guides/prompt-engineering',summary:'Consignes explicites, contexte, exemples et évaluation des résultats.'}
];
export const integrations=[
{id:'chatgpt',name:'ChatGPT',icon:'✳',description:'Votre atelier de rédaction, d’analyse et de préparation.',moduleId:'fondations',url:'https://chatgpt.com',steps:['Ouvrez ChatGPT avec votre propre compte. Les fonctions disponibles dépendent de votre abonnement.','Copiez un prompt du campus. Remplacez les variables avec des faits vérifiés et anonymisés.','Collez le prompt dans une nouvelle conversation. Demandez les informations manquantes avant la rédaction.','Comparez chaque affirmation aux sources, puis déposez votre livrable dans l’exercice.'],test:'Le résultat respecte la longueur, indique ses limites et n’ajoute aucun fait.'},
{id:'canva',name:'Canva',icon:'C',description:'Des carrousels, visuels et vidéos cohérents avec votre marque.',moduleId:'video',url:'https://www.canva.com',steps:['Créez un modèle avec vos couleurs, vos typographies et vos mentions professionnelles validées.','Demandez à ChatGPT un tableau : diapositive, titre, texte court, visuel, texte alternatif.','Copiez les textes dans le modèle et utilisez uniquement des visuels dont vous avez les droits.','Relisez sur mobile et exportez au format demandé par le canal choisi.'],test:'Le texte reste lisible et les images IA sont identifiées lorsque nécessaire.'},
{id:'make',name:'Make',icon:'M',description:'Du formulaire au CRM, avec validation et journal d’exécution.',moduleId:'automatisation',url:'https://www.make.com',steps:['Créez un scénario de test avec un webhook d’entrée et uniquement des données fictives.','Ajoutez un filtre qui vérifie le consentement pour la finalité de la campagne.','Recherchez le contact dans le CRM avant de créer ou mettre à jour sa fiche.','Créez une tâche de validation humaine ; activez le scénario après test des doublons, erreurs et retraits de consentement.'],test:'Deux événements identiques créent un seul contact et une seule tâche.'},
{id:'zapier',name:'Zapier',icon:'Z',description:'Des automatisations simples et documentées pour votre équipe.',moduleId:'automatisation',url:'https://zapier.com',steps:['Choisissez un déclencheur sur votre formulaire et connectez un compte de test.','Ajoutez Filter pour le consentement, puis Find Contact avant Create Contact.','Ajoutez une étape qui crée un brouillon ou une tâche, sans envoi automatique au premier essai.','Testez le cas nominal et le cas sans consentement ; documentez la procédure d’arrêt.'],test:'Aucun message marketing n’est envoyé en l’absence de consentement approprié.'},
{id:'crm',name:'HubSpot / votre CRM',icon:'H',description:'Une fiche client claire et un suivi que vous maîtrisez.',moduleId:'automatisation',url:'https://www.hubspot.com',steps:['Créez les champs : identifiant, provenance, consentement, date, finalité et prochaine action.','Définissez les étapes du pipeline avec une condition précise pour chaque transition.','Utilisez ChatGPT pour préparer des brouillons anonymisés, puis validez dans le CRM.','Restreignez les accès par rôle et vérifiez régulièrement les exports.'],test:'Un contact désabonné reste exclu même après une nouvelle synchronisation.'},
{id:'mail',name:'Brevo / Mailchimp',icon:'@',description:'Des infolettres segmentées et un désabonnement respecté.',moduleId:'infolettre',url:'https://www.brevo.com',steps:['Authentifiez votre domaine selon les instructions officielles de votre outil.','Importez seulement les destinataires pour lesquels une base de consentement a été vérifiée.','Insérez l’identité de l’expéditeur et le mécanisme de désabonnement natif.','Envoyez un test à vous-même, testez le retrait et vérifiez sa propagation dans le CRM.'],test:'Le clic de désabonnement empêche les envois suivants de la séquence.'},
{id:'gpt',name:'GPT personnalisé & Actions',icon:'↗',description:'Connectez un assistant à une API avec des accès limités.',moduleId:'automatisation',url:'https://developers.openai.com/api/docs/actions/introduction',steps:['Écrivez les instructions et les limites de votre GPT dans le constructeur disponible sur votre compte.','Importez le schéma OpenAPI de votre propre service, avec une URL HTTPS réelle.','Configurez l’authentification côté service ; commencez par une action de lecture et des données fictives.','Vérifiez les droits de chaque utilisateur côté serveur et demandez confirmation avant toute écriture.'],test:'Un utilisateur ne peut pas récupérer la fiche ou le travail d’un autre utilisateur.'},
{id:'visio',name:'Zoom / Google Meet / Teams',icon:'▷',description:'Des séances en direct avec votre administrateur.',moduleId:'automatisation',url:'https://meet.google.com',steps:['L’administrateur crée une réunion dans son outil de visioconférence.','Il ajoute le lien HTTPS, la date, la durée et la capacité dans Coaching du campus.','Les membres réservent leur place et retrouvent le lien dans leur session.','Activez la salle d’attente. Obtenez les autorisations nécessaires avant tout enregistrement.'],test:'Une réservation apparaît côté membre et côté administrateur.'}
];
