'use client';
import {useState,useEffect} from 'react';
import {autonomousCatalog,autonomousChapters} from '@/content/autonomous-catalog';
import {api,download} from './learning';
const criteria=['Exactitude','Respect des consignes','Traçabilité','Utilisabilité','Effort de correction'];
export default function Autonomous({access,go,progress,refresh,notify}:any){
 const [id,select]=useState(''),[lesson,L]=useState<any>(null),[error,E]=useState(''),[answers,A]=useState<number[]>([]),[result,R]=useState<any>(null),[draft,D]=useState<Record<string,any>>({}),[busy,B]=useState(false),[pace,P]=useState('25'),[goal,G]=useState('Marketing');
 const done=(key:string)=>progress.attempts?.some((a:any)=>a.lesson_id===key&&a.score>=80);
 const count=autonomousCatalog.filter(l=>done(l.id)).length;
 useEffect(()=>{if(!id)return;let alive=true;L(null);E('');A([]);R(null);const saved=progress.notes?.find((n:any)=>n.lesson_id===id);try{D(saved?JSON.parse(saved.body):{})}catch{D({})}api('autonomous?id='+id).then(l=>{if(alive)L(l)}).catch(e=>{if(alive)E(e.message)});return()=>{alive=false}},[id]);
 const update=(key:string,value:any)=>D(d=>({...d,[key]:value}));
 async function save(){B(true);try{await api('note',{lessonId:id,body:JSON.stringify(draft)});await refresh();notify('Votre comparaison est enregistrée dans votre compte.')}catch(e:any){notify(e.message)}finally{B(false)}}
 async function quiz(){B(true);try{R(await api('quiz',{lessonId:id,answers}));await refresh()}catch(e:any){notify(e.message)}finally{B(false)}}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);notify('Prompt copié.')}catch{notify('Copie indisponible : sélectionnez le texte du prompt.')}}
 if(!access)return <div className="panel"><h1>Claude + ChatGPT, en autonomie</h1><p>28 ateliers, pratique dans les deux outils et comparaison guidée. Votre accès membre actif ouvre ce parcours.</p><button className="button" onClick={()=>go('subscription')}>Voir mon accès</button></div>;
 return <div className="autonomous"><div className="eyebrow">FORMATION AUTONOME · DEUX OUTILS, VOTRE JUGEMENT</div><h1>Claude + ChatGPT</h1><p className="auto-intro">Apprenez, testez les deux, comparez et corrigez. 28 ateliers à votre rythme ; aucun rendez-vous nécessaire. Les essais se font dans vos comptes externes, dont les abonnements ne sont pas inclus.</p><div className="auto-progress"><progress max={28} value={count} aria-label="Ateliers dont le QCM est réussi"/><span>{count}/28 QCM réussis · seuil 80 %</span></div>
 {!id?<><section className="panel auto-plan"><h2>Votre rythme de travail</h2><div className="grid-two"><label>Temps par séance<select value={pace} onChange={e=>P(e.target.value)}><option value="15">15 minutes</option><option value="25">25 minutes</option><option value="50">50 minutes</option></select></label><label>Votre priorité<select value={goal} onChange={e=>G(e.target.value)}><option>Marketing</option><option>Organisation</option><option>Analyse de documents</option></select></label></div><p>{pace==='15'?'Prévoyez deux séances par atelier : comprendre, puis comparer.':pace==='50'?'Vous pouvez regrouper deux ateliers courts par séance.':'Prévoyez un atelier par séance, selon votre familiarité avec les outils.'} Pour {goal.toLowerCase()}, commencez par les bases puis explorez {goal==='Marketing'?'les ateliers 13 à 20':goal==='Organisation'?'les ateliers 21 à 26':'les ateliers 9 à 12'}. Le défi final demande environ une heure.</p><button className="button" onClick={()=>select(autonomousCatalog.find(l=>!done(l.id))?.id||'auto-01')}>Reprendre ma progression →</button></section>{autonomousChapters.map(ch=><section key={ch} className="auto-chapter"><h2>{ch}</h2><div className="auto-catalog">{autonomousCatalog.filter(l=>l.chapter===ch).map(l=><button key={l.id} onClick={()=>select(l.id)}><small>ATELIER {l.day} · ENV. {l.minutes} MIN</small><strong>{l.title}</strong><span>{done(l.id)?'✓ QCM réussi':'Claude + ChatGPT →'}</span></button>)}</div></section>)}<section className="panel"><h2>Votre bilan</h2><p>Les QCM évaluent la compréhension. Le carnet comparatif conserve votre pratique et votre auto-évaluation ; il ne constitue pas une certification professionnelle ni un crédit OACIQ.</p><button className="button outline" onClick={()=>download('bilan-autonomie.txt',autonomousCatalog.map(l=>`${l.title} : ${done(l.id)?'QCM réussi':'à travailler'}\n${progress.notes?.find((n:any)=>n.lesson_id===l.id)?.body||'Aucun carnet enregistré'}`).join('\n\n'))}>Exporter mon bilan</button></section></>:<><button className="text-button" onClick={()=>select('')}>← Tous les ateliers</button>{error?<div className="notice" role="alert">{error}</div>:!lesson?<p>Chargement de l’atelier…</p>:<>
 <h2 className="auto-lesson-title">{lesson.day}. {lesson.title}</h2><section className="panel prose"><h3>Comprendre</h3><p>{lesson.explanation}</p><h3>Votre cas fictif</h3><p>{lesson.scenario}</p><h3>Votre livrable</h3><p>{lesson.exercise}</p><ol><li>Préparez votre première réponse sans IA et identifiez les inconnues.</li><li>Ouvrez une nouvelle conversation dans chaque outil, avec le même cas et les mêmes fonctions disponibles.</li><li>Exécutez le prompt ci-dessous dans chacun. Conservez les versions et les réponses.</li><li>Appliquez la relance de contrôle, puis vérifiez vous-même les faits et les calculs.</li><li>Complétez le carnet, sauvegardez et passez le QCM.</li></ol></section>
 <div className="auto-pair">{(['chatgpt','claude'] as const).map(tool=><section className="panel" key={tool}><h3>{tool==='chatgpt'?'Avec ChatGPT':'Avec Claude'}</h3><p>Le même prompt de départ permet une comparaison équitable. Notez les différences de fonctions réellement disponibles dans votre compte.</p><pre className="auto-prompt">{lesson.prompts[tool]}</pre><div className="row"><button className="button small" onClick={()=>copy(lesson.prompts[tool])}>Copier le prompt</button><a className="text-button" href={tool==='chatgpt'?'https://chatgpt.com/':'https://claude.ai/'} target="_blank" rel="noreferrer">Ouvrir {tool==='chatgpt'?'ChatGPT':'Claude'} ↗</a></div></section>)}</div>
 <section className="panel"><h3>La deuxième passe</h3><p>{lesson.followup}</p><button className="text-button" onClick={()=>copy(lesson.followup)}>Copier la relance</button></section>
 <section className="panel"><h3>Comparer sur des preuves</h3><p>{lesson.comparison}</p><details><summary>Repères pour votre auto-correction</summary><p>{lesson.reference}</p></details><div className="auto-pair">{['ChatGPT','Claude'].map(tool=><div key={tool}><h4>{tool}</h4><label>Version affichée et fonctions utilisées<input value={draft[tool+'version']||''} maxLength={200} onChange={e=>update(tool+'version',e.target.value)}/></label><label>Résultat obtenu (extrait fictif)<textarea value={draft[tool]||''} maxLength={2200} onChange={e=>update(tool,e.target.value)}/></label><label>Minutes de correction<input type="number" min="0" max="999" value={draft[tool+'time']??''} onChange={e=>update(tool+'time',e.target.value)}/></label>{criteria.map(c=><label key={c}>{c}<select value={draft[tool+c]??''} onChange={e=>update(tool+c,e.target.value)}><option value="">Non évalué</option><option value="0">0 — insuffisant</option><option value="1">1 — à corriger</option><option value="2">2 — satisfaisant</option></select></label>)}</div>)}</div><label>Votre choix pour cette tâche, ses preuves et ses limites<textarea maxLength={2000} value={draft.conclusion||''} onChange={e=>update('conclusion',e.target.value)}/></label><p>Ces notes sont votre auto-évaluation, pas un classement automatique des modèles. Pour l’effort, 2 signifie peu de corrections.</p><button className="button" disabled={busy} onClick={save}>Enregistrer ma comparaison</button></section>
 <section className="panel"><h3>Vérifier vos acquis</h3>{lesson.questions.map((q:any,i:number)=><fieldset key={i}><legend>{i+1}. {q.question}</legend>{q.options.map((o:string,j:number)=><label key={j}><input type="radio" name={'auto-q'+i} checked={answers[i]===j} onChange={()=>{A(a=>{const next=[...a];next[i]=j;return next});R(null)}}/>{o}</label>)}{result&&<p className="feedback">{result.corrections[i].answer===answers[i]?'✓':'À revoir'} {result.corrections[i].explanation}</p>}</fieldset>)}<button className="button" disabled={busy||lesson.questions.some((_:any,i:number)=>answers[i]===undefined)} onClick={quiz}>Corriger mon QCM</button>{result&&<p role="status">{result.score}/100 · {result.passed?'Réussi':'Relisez les corrections et réessayez'}</p>}</section>
 <section className="panel"><h3>Repères produit</h3><p>Fonctions et limites variables selon le compte. Vérifiez la documentation avant chaque nouvel essai.</p><a className="source-link" href="https://help.openai.com/en/articles/10169521-projects-in-chatgpt" target="_blank" rel="noreferrer">Projets ChatGPT ↗</a><a className="source-link" href="https://support.claude.com/en/articles/9519177-how-can-i-create-and-manage-projects" target="_blank" rel="noreferrer">Projets Claude ↗</a><a className="source-link" href="https://support.claude.com/en/articles/9487310-what-are-artifacts-and-how-do-i-use-them" target="_blank" rel="noreferrer">Artifacts Claude ↗</a></section><div className="row"><button className="text-button" onClick={()=>select('')}>Retour au programme</button>{lesson.day<28&&<button className="button" onClick={()=>{select(autonomousCatalog[lesson.day].id);window.scrollTo(0,0)}}>Atelier suivant →</button>}</div></>}</>}
 </div>
}
