import fs from 'node:fs';import assert from 'node:assert/strict';import {neon} from '@neondatabase/serverless';import bcrypt from 'bcryptjs';import {randomBytes} from 'node:crypto';
process.loadEnvFile('.env.local');const sql=neon(process.env.DATABASE_URL);const base=process.env.TEST_URL||'http://localhost:3000';const accounts=JSON.parse(fs.readFileSync('../../admin-test-access.json','utf8'));const email='access-test-'+randomBytes(5).toString('hex')+'@example.invalid',password=randomBytes(20).toString('hex');let testId;
async function get(path,cookie='',status=200){const r=await fetch(base+'/api/'+path,{headers:cookie?{cookie}:{}});assert.equal(r.status,status,path);return r.json()}
async function login(a){const r=await fetch(base+'/api/auth/login',{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify(a)});assert.equal(r.status,200,'login');return r.headers.get('set-cookie').split(';')[0]}
try{const html=await(await fetch(base)).text();assert.ok(html.includes('Votre expertise immobilière.'));assert.ok(html.includes('POUR LES AGENCES'));assert.ok(!html.includes('VOTRE CAMPUS'));assert.ok(!html.includes('Agis comme assistant'));await get('prompts','',401);await get('lesson?id=v2-01','',403);await get('lesson?id=v2-13','',403);
const rows=await sql`INSERT INTO users(email,name,password_hash) VALUES(${email},'Compte temporaire de validation',${await bcrypt.hash(password,12)}) RETURNING id`;testId=rows[0].id;const inactive=await login({email,password});await get('prompts',inactive,403);await get('lesson?id=v2-01',inactive,403);const w=await fetch(base+'/api/quiz',{method:'POST',headers:{origin:base,'content-type':'application/json',cookie:inactive},body:JSON.stringify({lessonId:'v2-01',answers:[1,1]})});assert.equal(w.status,403,'inactive quiz');
for(const a of accounts){const cookie=await login(a);assert.equal((await get('prompts',cookie)).length,48);assert.equal((await get('lesson?id=v2-01',cookie)).id,'v2-01');}
console.log('PASS: accueil commercial sans campus; prompts et premières leçons bloqués anonymes et comptes sans accès; QCM bloqué sans accès; admin et membre invité conservent les 48 prompts.');
}finally{if(testId)await sql`DELETE FROM users WHERE id=${testId}`;}

